import { zipSync } from 'fflate';
import { ensureFontsLoaded } from './fonts';
import { CropCache, type LoadedImage } from './images';
import { encodePng24, readPngColorType } from './png';
import { PRESETS } from './playstore';
import { resolveSlide } from './project';
import { renderSlide } from './render';
import type { Project, Slide } from './types';

export type ExportFormat = 'png24' | 'jpeg';

export interface ExportedAsset {
  filename: string;
  bytes: Uint8Array;
  width: number;
  height: number;
  /** PNG colour type, for the assertion in the test suite. 2 = truecolour. */
  colorType: number | null;
}

export interface ExportOptions {
  format?: ExportFormat;
  /** JPEG quality, 0..1. Ignored for PNG. */
  quality?: number;
  onProgress?: (done: number, total: number) => void;
}

/**
 * Renders one slide at full export resolution onto a detached canvas.
 *
 * Deliberately creates a fresh canvas per slide rather than reusing one: a
 * 1600x2560 tablet asset holds 16 MB of pixel data, and keeping eight of those
 * alive at once is what makes this kind of tool crash on a mid-range phone.
 */
export function renderToCanvas(
  project: Project,
  slide: Slide,
  image: LoadedImage | null,
  crops: CropCache,
): HTMLCanvasElement {
  const preset = PRESETS[project.presetId];
  const canvas = document.createElement('canvas');
  canvas.width = preset.width;
  canvas.height = preset.height;

  const ctx = canvas.getContext('2d', { alpha: false });
  if (!ctx) throw new Error('This browser did not provide a 2D canvas context.');

  // Opaque base. Play rejects alpha, and `alpha: false` alone does not
  // guarantee every pixel was written.
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  const cropped = image ? crops.get(image, slide.cropTop) : null;

  renderSlide(ctx, {
    width: preset.width,
    height: preset.height,
    resolved: resolveSlide(project, slide, image?.palette ?? null),
    image: cropped?.source ?? null,
    imageWidth: cropped?.width ?? 0,
    imageHeight: cropped?.height ?? 0,
    dpr: 1,
  });

  return canvas;
}

function canvasToJpeg(canvas: HTMLCanvasElement, quality: number): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (!blob) {
          reject(new Error('The browser could not encode this canvas as JPEG.'));
          return;
        }
        blob.arrayBuffer().then((buf) => resolve(new Uint8Array(buf)), reject);
      },
      'image/jpeg',
      quality,
    );
  });
}

export function assetFilename(project: Project, index: number, extension: string): string {
  const preset = PRESETS[project.presetId];
  const slug =
    project.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 40) || 'app';
  const n = String(index + 1).padStart(2, '0');
  return preset.id === 'feature-graphic'
    ? `${slug}-feature-graphic-${preset.width}x${preset.height}.${extension}`
    : `${slug}-${preset.id}-${n}-${preset.width}x${preset.height}.${extension}`;
}

export async function exportSlide(
  project: Project,
  index: number,
  image: LoadedImage | null,
  crops: CropCache,
  options: ExportOptions = {},
): Promise<ExportedAsset> {
  const slide = project.slides[index];
  if (!slide) throw new Error(`No slide at index ${index}.`);

  await ensureFontsLoaded(
    [project.typography.headlineFont, project.typography.bodyFont],
    [project.typography.headlineWeight, 500, 600],
  );

  const canvas = renderToCanvas(project, slide, image, crops);
  const format = options.format ?? 'png24';

  if (format === 'jpeg') {
    const bytes = await canvasToJpeg(canvas, options.quality ?? 0.94);
    return {
      filename: assetFilename(project, index, 'jpg'),
      bytes,
      width: canvas.width,
      height: canvas.height,
      colorType: null,
    };
  }

  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Lost the canvas context before export.');
  const { data } = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const bytes = encodePng24(data, canvas.width, canvas.height);

  return {
    filename: assetFilename(project, index, 'png'),
    bytes,
    width: canvas.width,
    height: canvas.height,
    colorType: readPngColorType(bytes),
  };
}

/**
 * A plain-text checklist written into the ZIP.
 *
 * Someone downloads this folder, opens Play Console a week later and cannot
 * remember which slot each file belongs in. The note answers that without
 * needing the site again.
 */
export function buildReadme(project: Project, assets: ExportedAsset[]): string {
  const preset = PRESETS[project.presetId];
  const lines = [
    `${project.name} — Play Store assets`,
    `Generated by StoreShot on ${new Date().toISOString().slice(0, 10)}`,
    '',
    `Asset type : ${preset.label}`,
    `Dimensions : ${preset.width} x ${preset.height} px`,
    `Format     : 24-bit PNG, no alpha channel`,
    `Count      : ${assets.length} (Play accepts ${preset.minCount}-${preset.maxCount})`,
    '',
    'Where these go in Play Console:',
    '  Play Console > your app > Grow > Store presence > Main store listing',
    '',
    'Files, in the order they should be uploaded:',
    ...assets.map((a, i) => `  ${String(i + 1).padStart(2, '0')}. ${a.filename}`),
    '',
    'Notes:',
    '  - Play shows the first 2-3 screenshots without the user scrolling.',
    '    Put your strongest one first.',
    '  - These are 24-bit PNGs with the alpha channel removed, which is what',
    '    Play requires. Re-saving them in an image editor can add alpha back.',
    '  - Upload tablet screenshots as well if your app runs on tablets;',
    '    listings without them can rank lower on large screens.',
    '',
    'Asset specifications change. Confirm the current requirements in Play',
    'Console before you publish.',
  ];
  return lines.join('\n');
}

export async function exportAll(
  project: Project,
  images: Map<string, LoadedImage>,
  crops: CropCache,
  options: ExportOptions = {},
): Promise<{ blob: Blob; assets: ExportedAsset[]; filename: string }> {
  const assets: ExportedAsset[] = [];
  const total = project.slides.length;

  // Sequential on purpose: see renderToCanvas.
  for (let i = 0; i < total; i += 1) {
    const slide = project.slides[i]!;
    const image = slide.imageId ? images.get(slide.imageId) ?? null : null;
    assets.push(await exportSlide(project, i, image, crops, options));
    options.onProgress?.(i + 1, total);
  }

  const files: Record<string, Uint8Array> = {};
  for (const asset of assets) files[asset.filename] = asset.bytes;
  files['README.txt'] = new TextEncoder().encode(buildReadme(project, assets));

  // level 0: the PNGs are already deflated, so re-compressing them only costs
  // time. The README is a rounding error.
  const zipped = zipSync(files, { level: 0 });
  const slug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'app';

  return {
    blob: new Blob([zipped as unknown as BlobPart], { type: 'application/zip' }),
    assets,
    filename: `${slug}-${project.presetId}-assets.zip`,
  };
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function downloadAsset(asset: ExportedAsset): void {
  const type = asset.filename.endsWith('.png') ? 'image/png' : 'image/jpeg';
  downloadBlob(new Blob([asset.bytes as unknown as BlobPart], { type }), asset.filename);
}
